spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.77.36:33306/plus?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis-plus:
  type-aliases-package: com.abc.mybatisplus.entity
  mapper-locations: classpath:/mapper/*.xml