server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.77.36:33306/shiro?&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  redis:
    host: 81.70.77.36
    port: 16379
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.abc.shiro.entity